#!/usr/bin/env zsh

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  successfully open https://github.com/account/ssh

echo "Fixing permissions ..."
  successfully sudo chown -R `whoami` /usr/local

echo "Grabbing Dotfiles"
  succesfully git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
  succesfully source $HOME/.homesick/repos/homeshick/homeshick.sh && homeshick clone git@github.com:NickTomlin/dotfiles.git

echo "Cloning Vundle"
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

echo "Putting Homebrew location earlier in PATH ..."
  successfully echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshenv
  successfully source ~/.zshenv

echo "Installing a *lot* of applications via homebrew"
  succesfully sh brew-install.sh

echo "Setting a lot of osx defaults. You will be asked for your password"
  succesfully sh osx-defaults.sh
